-- MySQL Script generated by MySQL Workbench
-- Mon Jun 14 01:22:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema almacen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema almacen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `almacen` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `almacen` ;

-- -----------------------------------------------------
-- Table `almacen`.`maestro_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`maestro_almacen` (
  `id_maestro_almacen` INT NOT NULL AUTO_INCREMENT,
  `nombre_almacen` VARCHAR(250) NOT NULL,
  `ubicacion` VARCHAR(250) NOT NULL,
  `maestro_almacen_descripcion` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_maestro_almacen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `almacen`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`personas` (
  `id_personas` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ap_paterno` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ap_maternol` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CI` INT NOT NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  PRIMARY KEY (`id_personas`),
  UNIQUE INDEX `CI_UNIQUE` (`CI` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `almacen`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuariol` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `tipo_usuario_descripcion` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `almacen`.`maestro_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`maestro_usuario` (
  `id_maestro_usuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fecha_creacion_usuario` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estatus` CHAR(8) NULL DEFAULT 'activo',
  `id_tipo_usuario` INT NOT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_maestro_usuario`),
  INDEX `usuarios_personas_idx` (`id_persona` ASC) VISIBLE,
  INDEX `usuarios_tipo_usuarios_idx` (`id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `usuarios_personas`
    FOREIGN KEY (`id_persona`)
    REFERENCES `almacen`.`personas` (`id_personas`)
    ON UPDATE CASCADE,
  CONSTRAINT `usuarios_tipo_usuarios`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `almacen`.`tipo_usuario` (`id_tipo_usuario`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `almacen`.`master_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`master_empresa` (
  `id_master_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(250) NOT NULL,
  `NIT` VARCHAR(45) NOT NULL,
  `tipo_empresa` VARCHAR(250) NOT NULL,
  `maestro_usuario_id_maestro_usuario` INT NOT NULL,
  PRIMARY KEY (`id_master_empresa`),
  INDEX `fk_master_empresa_maestro_usuario1_idx` (`maestro_usuario_id_maestro_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_master_empresa_maestro_usuario1`
    FOREIGN KEY (`maestro_usuario_id_maestro_usuario`)
    REFERENCES `almacen`.`maestro_usuario` (`id_maestro_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `almacen`.`almacen_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`almacen_empresa` (
  `id_almacen_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre_almacen` VARCHAR(250) NOT NULL,
  `direccion_almacen_empresa` VARCHAR(250) NOT NULL,
  `activo` CHAR(8) NOT NULL DEFAULT 'activo',
  `maestro_almacen_id_maestro_almacen` INT NOT NULL,
  `master_empresa_id_master_empresa` INT NOT NULL,
  PRIMARY KEY (`id_almacen_empresa`),
  INDEX `fk_almacen_empresa_maestro_almacen1_idx` (`maestro_almacen_id_maestro_almacen` ASC) VISIBLE,
  INDEX `fk_almacen_empresa_master_empresa1_idx` (`master_empresa_id_master_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_almacen_empresa_maestro_almacen1`
    FOREIGN KEY (`maestro_almacen_id_maestro_almacen`)
    REFERENCES `almacen`.`maestro_almacen` (`id_maestro_almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_almacen_empresa_master_empresa1`
    FOREIGN KEY (`master_empresa_id_master_empresa`)
    REFERENCES `almacen`.`master_empresa` (`id_master_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `almacen`.`master_materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`master_materiales` (
  `id_master_materiales` INT NOT NULL AUTO_INCREMENT,
  `nombre_material` VARCHAR(250) NOT NULL,
  `unidad_material` VARCHAR(45) NOT NULL,
  `descripcion_material` VARCHAR(250) NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_master_materiales`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `almacen`.`materiales_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`materiales_almacen` (
  `id_materiales_almacen` INT NOT NULL AUTO_INCREMENT,
  `cantidad` FLOAT(5,2) NOT NULL,
  `ubicacion` VARCHAR(250) NOT NULL,
  `observaciones` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id_materiales_almacen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `almacen`.`tipo_proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`tipo_proyectos` (
  `id_tipo_proyectos` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_proyecto` VARCHAR(250) NOT NULL,
  `descripcion_tipo_proyecto` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_tipo_proyectos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacen`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`proyectos` (
  `id_proyectos` INT NOT NULL AUTO_INCREMENT,
  `nombre_proyecto` VARCHAR(150) NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `monto_proyecto` FLOAT(9,2) NOT NULL,
  `tipo_proyectos_id_tipo_proyectos` INT NOT NULL,
  PRIMARY KEY (`id_proyectos`),
  INDEX `fk_proyectos_tipo_proyectos1_idx` (`tipo_proyectos_id_tipo_proyectos` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_tipo_proyectos1`
    FOREIGN KEY (`tipo_proyectos_id_tipo_proyectos`)
    REFERENCES `almacen`.`tipo_proyectos` (`id_tipo_proyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacen`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`Item` (
  `id_Item` INT NOT NULL AUTO_INCREMENT,
  `nombre_item` VARCHAR(250) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  `proyectos_id_proyectos` INT NOT NULL,
  PRIMARY KEY (`id_Item`),
  INDEX `fk_Item_proyectos1_idx` (`proyectos_id_proyectos` ASC) VISIBLE,
  CONSTRAINT `fk_Item_proyectos1`
    FOREIGN KEY (`proyectos_id_proyectos`)
    REFERENCES `almacen`.`proyectos` (`id_proyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacen`.`materiales_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`materiales_item` (
  `id_materiales_item` INT NOT NULL AUTO_INCREMENT,
  `cantidad` FLOAT(6,2) NOT NULL,
  `rendimiento` FLOAT(6,2) NOT NULL,
  `Item_id_Item` INT NOT NULL,
  PRIMARY KEY (`id_materiales_item`),
  INDEX `fk_materiales_item_Item1_idx` (`Item_id_Item` ASC) VISIBLE,
  CONSTRAINT `fk_materiales_item_Item1`
    FOREIGN KEY (`Item_id_Item`)
    REFERENCES `almacen`.`Item` (`id_Item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacen`.`mm_ma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`mm_ma` (
  `idmm_ma` INT NOT NULL AUTO_INCREMENT,
  `master_materiales_id_master_materiales` INT NOT NULL,
  `materiales_almacen_id_materiales_almacen` INT NOT NULL,
  PRIMARY KEY (`idmm_ma`),
  INDEX `fk_mm_ma_master_materiales1_idx` (`master_materiales_id_master_materiales` ASC) VISIBLE,
  INDEX `fk_mm_ma_materiales_almacen1_idx` (`materiales_almacen_id_materiales_almacen` ASC) VISIBLE,
  CONSTRAINT `fk_mm_ma_master_materiales1`
    FOREIGN KEY (`master_materiales_id_master_materiales`)
    REFERENCES `almacen`.`master_materiales` (`id_master_materiales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mm_ma_materiales_almacen1`
    FOREIGN KEY (`materiales_almacen_id_materiales_almacen`)
    REFERENCES `almacen`.`materiales_almacen` (`id_materiales_almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacen`.`ae_ma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`ae_ma` (
  `idae_ma` INT NOT NULL AUTO_INCREMENT,
  `almacen_empresa_id_almacen_empresa` INT NOT NULL,
  `materiales_almacen_id_materiales_almacen` INT NOT NULL,
  PRIMARY KEY (`idae_ma`),
  INDEX `fk_ae_ma_almacen_empresa1_idx` (`almacen_empresa_id_almacen_empresa` ASC) VISIBLE,
  INDEX `fk_ae_ma_materiales_almacen1_idx` (`materiales_almacen_id_materiales_almacen` ASC) VISIBLE,
  CONSTRAINT `fk_ae_ma_almacen_empresa1`
    FOREIGN KEY (`almacen_empresa_id_almacen_empresa`)
    REFERENCES `almacen`.`almacen_empresa` (`id_almacen_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ae_ma_materiales_almacen1`
    FOREIGN KEY (`materiales_almacen_id_materiales_almacen`)
    REFERENCES `almacen`.`materiales_almacen` (`id_materiales_almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacen`.`mi_mm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`mi_mm` (
  `idmi_mm` INT NOT NULL AUTO_INCREMENT,
  `materiales_item_id_materiales_item` INT NOT NULL,
  `master_materiales_id_master_materiales` INT NOT NULL,
  PRIMARY KEY (`idmi_mm`),
  INDEX `fk_mi_mm_materiales_item1_idx` (`materiales_item_id_materiales_item` ASC) VISIBLE,
  INDEX `fk_mi_mm_master_materiales1_idx` (`master_materiales_id_master_materiales` ASC) VISIBLE,
  CONSTRAINT `fk_mi_mm_materiales_item1`
    FOREIGN KEY (`materiales_item_id_materiales_item`)
    REFERENCES `almacen`.`materiales_item` (`id_materiales_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mi_mm_master_materiales1`
    FOREIGN KEY (`master_materiales_id_master_materiales`)
    REFERENCES `almacen`.`master_materiales` (`id_master_materiales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacen`.`maestro_estado_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`maestro_estado_pedidos` (
  `idmaestro_estado_pedidos` INT NOT NULL AUTO_INCREMENT,
  `nombre_maestro_estado_pedido` VARCHAR(250) NOT NULL,
  `descrip_maestro_estado_pedidos` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idmaestro_estado_pedidos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacen`.`pedido_materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen`.`pedido_materiales` (
  `id_pedido_materiales` INT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` VARCHAR(45) NULL,
  `maestro_estado_pedidos_idmaestro_estado_pedidos` INT NOT NULL,
  `Item_id_Item` INT NOT NULL,
  PRIMARY KEY (`id_pedido_materiales`),
  INDEX `fk_pedido_materiales_maestro_estado_pedidos1_idx` (`maestro_estado_pedidos_idmaestro_estado_pedidos` ASC) VISIBLE,
  INDEX `fk_pedido_materiales_Item1_idx` (`Item_id_Item` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_materiales_maestro_estado_pedidos1`
    FOREIGN KEY (`maestro_estado_pedidos_idmaestro_estado_pedidos`)
    REFERENCES `almacen`.`maestro_estado_pedidos` (`idmaestro_estado_pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_materiales_Item1`
    FOREIGN KEY (`Item_id_Item`)
    REFERENCES `almacen`.`Item` (`id_Item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
